version: '3.5'

services:
  hop-server:
    image: apache/hop:2.7.0
    container_name: hop-server
    env_file:
      - .env
    volumes:
      - hop_projetos:/opt/projetos/
    ports:
      - "8182:8182"
    networks:
      - hop
      - postgres-prd

networks:
  hop:
    external: true
  postgres-prd:
    external: true

volumes:
  hop_projetos:
    external: true

